'use client'
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{useEffect,useState,useRef}from"react";import Papa from"papaparse";import{addPropertyControls,ControlType}from"framer";
function injectCSS(){if(!document.querySelector('link[href*="mapbox-gl.css"]')){const l=document.createElement("link");l.href="https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.css";l.rel="stylesheet";document.head.appendChild(l);}}
function loadMapboxGL(){return new Promise((resolve,reject)=>{if(window.mapboxgl){resolve(window.mapboxgl);return;}const script=document.createElement("script");script.src="https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.js";script.onload=()=>resolve(window.mapboxgl);script.onerror=reject;document.head.appendChild(script);});}
const haversine=(aLat,aLng,bLat,bLng)=>{const R=6371,d=Math.PI/180;const dLat=(bLat-aLat)*d;const dLng=(bLng-aLng)*d;const h=Math.sin(dLat/2)**2+Math.cos(aLat*d)*Math.cos(bLat*d)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));};
function escapeHTML(str){return String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function escapeAttribute(str){return String(str).replace(/"/g,"%22");}
function bestKeyMatch(row,pool){const lowerMap={};Object.keys(row).forEach(k=>{lowerMap[k.toLowerCase().replace(/\s+/g,"")]=k;});for(const p of pool){const found=lowerMap[p.toLowerCase()];if(found)return found;}return pool[0];}
export default function StoreLocator(props){const{data={},layout={},mapping={}}=props;const{sheetUrl,mapboxToken,styleUrl,centerLat,centerLng,radiusKm,initialZoom,popupOnHover,pinSvg}=data;const{sidebarWidth=300,mobileBreakpoint=768,showSidebar=true}=layout;const{cardTitle,cardDescription,popupTitle,popupDescription,popupContact,popupLink,popupImage,popupExtraFields=[]}=mapping;const mapDiv=useRef(null);const mapRef=useRef(null);const markersRef=useRef([]);const[rows,setRows]=useState([]);const[term,setTerm]=useState("");const[selRow,setSelRow]=useState(null);const[isMobile,setIsMobile]=useState(typeof window!=="undefined"?window.innerWidth<mobileBreakpoint:false);const[hoverIdx,setHoverIdx]=useState(null);const[mobileSelect,setMobileSelect]=useState(-1);
useEffect(()=>{const onResize=()=>setIsMobile(window.innerWidth<mobileBreakpoint);window.addEventListener("resize",onResize);return()=>window.removeEventListener("resize",onResize);},[mobileBreakpoint]);
useEffect(()=>{if(!sheetUrl)return;injectCSS();fetch(sheetUrl).then(r=>r.text()).then(txt=>{const parsed=Papa.parse(txt,{header:true});const allRows=parsed.data;const cleaned=allRows.filter(r=>{const latKey=bestKeyMatch(r,["lat","latitude"]);const lngKey=bestKeyMatch(r,["lng","lon","long","longitude"]);return r[latKey]&&r[lngKey]&&r[cardTitle];});const within=cleaned.filter(r=>{const lat=parseFloat(r[bestKeyMatch(r,["lat","latitude"])]);const lng=parseFloat(r[bestKeyMatch(r,["lng","lon","long","longitude"])]);return haversine(centerLat??0,centerLng??0,lat,lng)<=(radiusKm??2e4);});setRows(within);}).catch(e=>console.error("CSV load error:",e));},[sheetUrl,cardTitle,centerLat,centerLng,radiusKm]);
useEffect(()=>{if(!mapboxToken||!mapDiv.current)return;let alive=true;loadMapboxGL().then(mapboxgl=>{if(!alive)return;mapboxgl.accessToken=mapboxToken;const styleToUse=styleUrl||"mapbox://styles/mapbox/streets-v12";if(!mapRef.current){mapRef.current=new mapboxgl.Map({container:mapDiv.current,style:styleToUse,center:[centerLng??0,centerLat??0],zoom:initialZoom??2});mapRef.current.on("load",()=>{console.log("✅ Map loaded");});mapRef.current.on("error",e=>{console.error("❌ Map error:",e.error||e);});}}).catch(error=>{console.error("Failed to load Mapbox GL:",error);});return()=>{alive=false;};},[mapboxToken,styleUrl,centerLat,centerLng,initialZoom]);
useEffect(()=>{if(!mapRef.current)return;loadMapboxGL().then(mapboxgl=>{markersRef.current.forEach(m=>m.remove());markersRef.current=[];rows.forEach(r=>{const latKey=bestKeyMatch(r,["lat","latitude"]);const lngKey=bestKeyMatch(r,["lng","lon","long","longitude"]);const lat=parseFloat(r[latKey]);const lng=parseFloat(r[lngKey]);if(isNaN(lat)||isNaN(lng))return;let pinEl;if(pinSvg&&pinSvg.src){const img=document.createElement("img");img.src=pinSvg.src;img.style.width="24px";img.style.height="24px";pinEl=img;}else{const d=document.createElement("div");d.textContent="📍";d.style.fontSize="22px";pinEl=d;}pinEl.style.cursor="pointer";const marker=new mapboxgl.Marker(pinEl).setLngLat([lng,lat]);const nv=r[popupTitle]??"";const dv=r[popupDescription]??"";const cv=r[popupContact]??"";const lv=r[popupLink]??"";const iv=r[popupImage]??"";let html=`<div style="font-size:14px;color:#1A1A1A;line-height:1.3;"><div style="font-weight:600;margin-bottom:4px;">${escapeHTML(nv)}</div>`;if(iv){html+=`<div style="margin-bottom:8px;"><img src="${escapeAttribute(iv)}" style="width:100%;max-width:200px;height:auto;border-radius:4px;display:block;" alt="${escapeHTML(nv)}" onerror="this.style.display='none'" /></div>`;}if(dv)html+=`<div style="font-size:13px;color:#555;margin-bottom:4px;">${escapeHTML(dv)}</div>`;if(cv)html+=`<div style="font-size:13px;margin-bottom:4px;">${escapeHTML(cv)}</div>`;if(lv)html+=`<a href="${escapeAttribute(lv)}" target="_blank" style="font-size:13px;color:#007aff;text-decoration:none;">Visit website</a>`;popupExtraFields.forEach(fld=>{const lab=fld.fieldLabel||"";const col=fld.fieldColumn||"";const val=r[col]||"";if(lab&&val){html+=`<div style="font-size:13px;margin-bottom:4px;"><strong>${escapeHTML(lab)}:</strong> ${escapeHTML(val)}</div>`;}});html+=`</div>`;const pop=new mapboxgl.Popup({offset:20}).setHTML(html);marker.setPopup(pop).addTo(mapRef.current);if(popupOnHover){pinEl.addEventListener("mouseenter",()=>pop.addTo(mapRef.current));pinEl.addEventListener("mouseleave",()=>pop.remove());}markersRef.current.push(marker);});});},[rows,popupTitle,popupDescription,popupContact,popupLink,popupImage,popupExtraFields,pinSvg,popupOnHover]);
const fly=r=>{if(!r)return;const latKey=bestKeyMatch(r,["lat","latitude"]);const lngKey=bestKeyMatch(r,["lng","lon","long","longitude"]);const lat=parseFloat(r[latKey]);const lng=parseFloat(r[lngKey]);if(isNaN(lat)||isNaN(lng))return;setSelRow(r);mapRef.current?.flyTo({center:[lng,lat],zoom:12,essential:true});};
const visible=term?rows.filter(r=>{const n=(r[cardTitle]||"").toString().toLowerCase();const d=(r[cardDescription]||"").toString().toLowerCase();return n.includes(term.toLowerCase())||d.includes(term.toLowerCase());}):rows;
const sidebarCSS={background:"#fff",borderRight:"1px solid #e3e7ef",boxShadow:"0 1px 8px rgba(32,34,45,0.06)",padding:"20px 16px",display:"flex",flexDirection:"column",gap:10};
const cardCSS=(active,hover)=>({background:active||hover?"#f0f4fb":"#fff",border:"1px solid #e3e7ef",borderRadius:8,boxShadow:active?"0 2px 8px rgba(32,34,45,0.09)":"0 1px 4px rgba(32,34,45,0.06)",padding:"10px 12px",color:"#1c1e21",cursor:"pointer",transition:"background .16s,box-shadow .16s",display:"flex",flexDirection:"column"});
return /*#__PURE__*/_jsxs("div",{style:{width:"100%",height:"100%",display:"flex",flexDirection:isMobile?"column":"row"},children:[showSidebar&&/*#__PURE__*/_jsxs("div",{style:{width:isMobile?"100%":sidebarWidth,minWidth:isMobile?undefined:sidebarWidth,overflowY:"auto",...sidebarCSS},children:[/*#__PURE__*/_jsx("input",{placeholder:"Search…",value:term,onChange:e=>setTerm(e.target.value),style:{width:"100%",background:"#f8fafd",border:"1px solid #e3e7ef",borderRadius:8,fontSize:14,color:"#242629",padding:"8px 12px",outline:"none",boxShadow:"0 1px 2px rgba(30,40,70,0.03)",transition:"border .16s"}}),isMobile?/*#__PURE__*/_jsxs("select",{value:mobileSelect,onChange:e=>{const idx=+e.currentTarget.value;if(idx>=0&&idx<visible.length){setMobileSelect(idx);fly(visible[idx]);}},style:{width:"100%",padding:"8px",fontSize:14,marginBottom:10},children:[/*#__PURE__*/_jsx("option",{value:-1,disabled:true,children:"Select a location"}),visible.map((r,i)=>/*#__PURE__*/_jsx("option",{value:i,children:r[cardTitle]},i))]}):null,!isMobile?visible.map((r,i)=>{const active=selRow&&selRow[cardTitle]===r[cardTitle];const hover=hoverIdx===i;return /*#__PURE__*/_jsxs("div",{style:cardCSS(active,hover),onMouseEnter:()=>setHoverIdx(i),onMouseLeave:()=>setHoverIdx(null),onClick:()=>fly(r),children:[/*#__PURE__*/_jsx("div",{style:{fontWeight:600,fontSize:15,marginBottom:2},children:r[cardTitle]||""}),r[cardDescription]&&/*#__PURE__*/_jsx("div",{style:{fontSize:13,color:"#555"},children:r[cardDescription]})]},i);}):null]}),/*#__PURE__*/_jsx("div",{style:{flex:1,position:"relative"},children:/*#__PURE__*/_jsx("div",{ref:mapDiv,style:{width:"100%",height:"100%",boxSizing:"border-box"}})})]});}
StoreLocator.defaultProps={data:{sheetUrl:"",mapboxToken:"",styleUrl:"",centerLat:19.076,centerLng:72.8777,radiusKm:2e4,initialZoom:2,popupOnHover:false,pinSvg:{}},layout:{sidebarWidth:300,mobileBreakpoint:768,showSidebar:true},mapping:{cardTitle:"name",cardDescription:"address",popupTitle:"name",popupDescription:"address",popupContact:"phone",popupLink:"website",popupImage:"image",popupExtraFields:[]}};
addPropertyControls(StoreLocator,{data:{type:ControlType.Object,title:"Data"},layout:{type:ControlType.Object,title:"Layout"},mapping:{type:ControlType.Object,title:"Mapping"}});

